### ISSUE TITLE
Support ID Token Fetching With User Credentials

### ISSUE THREAD

**Issue by tilgovi** [googleapis/google-auth-library-nodejs#1551] opened 2023-05-18 17:38 UTC
Google auth libraries for other languages support getting identity tokens for an arbitrary audience with user credentials but this one does not. In addition to the language SDKs, `gcloud` CLI supports `print-identity-token --audiences=...`.

I'm filing this ticket as a feature request to clarify what I think is the underlying issue behind #1543 and the (closed but maybe shouldn't be) #1113.

The following should working after setting up application default credentials on a developer machine:

```javascript
import { auth } from 'google-auth-library';
await auth.getIdTokenClient('my-audience');
```

Perhaps it would be best if `auth.getRequestHeaders('audience')` also used the ID token client when the audience is not a Google API supporting Google access tokens, as is done with other credential types.

Lack of support for this provides friction for local development of any application that calls services using Identity-Aware Proxy or Cloud Endpoints with Google ID Token authentication.

**Comment by tilgovi** [comment] 2023-05-18 17:58
I may actually be wrong here, but want to consolidate a focused conversation on the subject.

Java library supports this, but it requires a cast:

```java
((IdTokenProvider)GoogleCredentials.getApplicationDefault()).idTokenWithAudience("audience", new ArrayList<IdTokenProvider.Option>())
```

Python library seems not to support this.

What's the intention? How are users of Google auth libraries meant to call services using IAP or Cloud Endpoints during local development without long-lived service account keys?

**Comment by tilgovi** [comment] 2023-05-23 20:17
The correct way to do this might be to use service account impersonation. For calling endpoints that use Cloud Endpoints or IAP, that might mean being explicit about the use of an ID token client, rather than assuming that the default credentials client is a self-signed JWT client.

Do:
```javascript
const client = await auth.getIdTokenClient(audience);
const headers = await client.getRequestHeaders(url);
```

Don't:
```javascript
const headers = await auth.getRequestHeaders(audience);
```

**Comment by keithw99** [comment] 2023-06-22 04:54
> Python library seems not to support this.
> 
Python actually does support this:
```python
import google.auth.transport.requests as google_requests
import google.oauth2.id_token

auth_req = google.auth.transport.requests.Request()
id_token = google.oauth2.id_token.fetch_id_token(auth_req, AUDIENCE)
```
This works 100% with user credentials downloaded from `gcloud auth application-default login`. No service account key needed, and no `GOOGLE_APPLICATION_CREDENTIALS` needed. However, a NodeJS client trying to do the exact same thing will fail with this exception:
```
Cannot fetch ID token in this environment, use GCE or set the GOOGLE_APPLICATION_CREDENTIALS environment variable to a service account credentials JSON file.
```
It seems that the NodeJS auth library is simply not at parity with the other Google auth libraries, and I agree that https://github.com/googleapis/google-auth-library-nodejs/issues/1113 should not be closed. At minimum, the NodeJS client library should clearly document that it does not support user credentials when developing locally.

**Comment by tilgovi** [comment] 2023-06-23 05:46
When I do that on my local machine I get a similar error to the Node.js library:

```
google.auth.exceptions.DefaultCredentialsError: Neither metadata server or valid service account credentials are found.
```

**Comment by keithw99** [comment] 2023-07-05 16:15
> When I do that on my local machine I get a similar error to the Node.js library:
> 
> ```
> google.auth.exceptions.DefaultCredentialsError: Neither metadata server or valid service account credentials are found.
> ```

Hmm, not sure what causes that. I updated my example with more context to illustrate how I used the fetched token in the request. I assume you are doing something similar?

**Comment by danielbankhead** [comment] 2023-07-14 20:19
This is a duplicate of https://github.com/googleapis/google-auth-library-nodejs/issues/876, let's continue the conversation there

**Closed by danielbankhead** 2023-07-14 20:19 UTC
Labels: type: feature request, priority: p3
