### ISSUE TITLE
'GoogleAuth<JSONClient> | undefined' is not assignable to type 'JSONClient | undefined'.

### ISSUE THREAD

**Issue by zubairzahoor** [googleapis/google-auth-library-nodejs#1374] opened 2022-02-23 06:20 UTC
Did the recent update break something?

 Types of property 'authClient' are incompatible.
11:08:51      Type 'GoogleAuth<JSONClient> | undefined' is not assignable to type 'JSONClient | undefined'.
11:08:51  node_modules/@google-cloud/common/build/src/util.d.ts(42,18): error TS2430: Interface 'MakeAuthenticatedRequestFactoryConfig' incorrectly extends interface 'GoogleAuthOptions<JSONClient>'.
11:08:51    Types of property 'authClient' are incompatible.
11:08:51      Type 'GoogleAuth<JSONClient> | undefined' is not assignable to type 'JSONClient | undefined'.
11:08:51        Type 'GoogleAuth<JSONClient>' is not assignable to type 'JSONClient | undefined'.
11:08:51          Type 'GoogleAuth<JSONClient>' is missing the following properties from type 'JWT': createScoped, getRequestMetadataAsync, fetchIdToken, hasUserScopes

Environment details
OS: CentOS
Node.js version: NodeJS_v12.18.2
@google-cloud/common version: 3.9.0

Steps to reproduce
A simple npm run build causes this.

**Comment by iPablo** [comment] 2022-02-23 15:16
I have the same issue since this morning

**Comment by bcoe** [comment] 2022-02-23 15:21
closing as duplicate of https://github.com/googleapis/nodejs-common/issues/734

`google-gax` has been rolled back, which was forcing the latest version of auth.

**Closed by bcoe** 2022-02-23 15:21 UTC
Labels: type: bug, priority: p2
