### ISSUE TITLE
Cloud functions Export/Import - A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account.

### ISSUE THREAD

**Issue by 39ro** [googleapis/google-auth-library-nodejs#532] opened 2018-11-15 20:53 UTC
I am trying to generate a snapshot of my Firestore database, while running the following code inside a Cloud Function, I receive a "Forbidden Error".
From my side, I can't see nothing else in my request that need to be added. 
```
const {auth} = require('google-auth-library');

async function main() {
    const client = await auth.getClient({
            scopes: [
                'https://www.googleapis.com/auth/datastore',
                'https://www.googleapis.com/auth/cloud-platform'
            ]
        }
    );
    const projectId = await auth.getProjectId();
    const url = `https://firestore.googleapis.com/v1beta1/projects/${projectId}/databases/(default):exportDocuments`;
    return client.request({
        url: url,
        method: 'post',
        data: {
            outputUriPrefix: 'gs://my-awesome-storage.appspot.com'
        }
    });
}
```

Could someone please clarify what it actually means?

```
Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. The caller does not have permission
```

- [https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases/exportDocuments#http-request](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases/exportDocuments#http-request)

#### Environment details
  - `google-auth-library` version: 2.0.1

**Comment by JustinBeckwith** [comment] 2018-12-07 00:35
Greetings!  This is a bit of a tricky one.  When I try this out for myself, everything seems to work.  Can you double check the permissions on the service account you're using to run your cloud function?  Is it using the default App Engine service account?

**Comment by acoulton** [comment] 2018-12-19 00:16
I also this evening spent a while trying to figure out the other variant of this error when running in CloudFunctions:

`Error: A Not Found error was returned while attempting to retrieve an accesstoken for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have any permission scopes specified.`

It took me a while to realise the issue was actually nothing at all to do with the accesstoken : I had actually entered the wrong API url. Fixing that URL solved the problem.

It looks like https://github.com/googleapis/google-auth-library-nodejs/blob/05e7adc85f8cfc16a65a2b8a44c879812d9fc1e1/src/auth/computeclient.ts#L86 is potentially firing on **any** 403/404 rather than just ones related to getting a token?

**Comment by torbjornvatn** [comment] 2018-12-20 14:37
I don't enter the URL manually though, but rather call the export endpoint like this
```javascript
 firestore.projects.databases.exportDocuments({
        name: `projects/${projectId}/databases/${projectId}`,
        requestBody: {"outputUriPrefix": `gs://${backupBucket}`}
 })
```
And I've added these scopes:
```javascript
scopes: [
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/datastore',
            'https://www.googleapis.com/auth/compute'
        ],
```

**Comment by torbjornvatn** [comment] 2018-12-20 16:50
I also tried changing the name part to `name: 'projects/${projectId}/databases/(default)'` to use the default database feature, but got the same error

**Comment by javiermuniz** [comment] 2019-01-19 04:53
@JustinBeckwith I'm having the same issue when running from functions, oddly when I download the json file, set env, and make the same call locally I'm getting "The caller does not have permission" 

This is using the json key file from the App Engine service account. I've tried using the client.request() method as well as the exportDocuments method within the firestore namespace in googleapis. Both yield the same result.

**Comment by javiermuniz** [comment] 2019-01-21 06:57
@torbjornvatn the PrIoject Editor role, and therefore the default App Engine service account, is not enough to perform backups. Try going into IAM and adding the Cloud Datastore Import Export Admin role to your App Engine service account. This fixed the issue for me.

**Comment by JustinBeckwith** [comment] 2019-01-21 08:13
Greetings folks!  I suspect the problem y'all are running into is independent of this library.  It sounds like a case of trying to use an API that the service account doesn't have access to.  If you're still running into issues - please do let me know!  Otherwise - I'm closing this out for now.

**Comment by acoulton** [comment] 2019-01-21 09:42
@JustinBeckwith the *root* cause is the absence of permissions on the service account, or in my case just using the wrong URL for an API.

But per my comment above the problem is that this library at https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/computeclient.ts#L92 discards any error message returned from the API.

Instead for all 403 or 404 it just returns a generic message about an error `while attempting to retrieve an access token for the Compute Engine built-in service account`.

This causes confusion and means the user doesn't see the actual error returned by the API (which I think in the case of a 403 usually mentions the permission that is required). I spent a lot of time trying to debug permissions things before I realised I'd just got a typo in the URL.

**Comment by jpotterm** [comment] 2019-03-07 22:41
I'll second what @acoulton said. The discarding of any error messages from the API makes mistakes really hard to debug.

**Comment by jpotterm** [comment] 2019-03-07 23:45
A workaround I found is to use the `getRequestHeaders` function from this library and then send the request through something like axios instead. That will let you see the error message.

**Comment by JustinBeckwith** [comment] 2019-04-12 00:52
Thanks for sticking with me here folks.  I submitted #668, which *should* do a better job of surfacing the underlying exception.  I think this is the last of the exceptions we were eating and not re-throwing in the code base.

**Closed** 2019-04-12 06:37 UTC
Labels: needs more info, type: question

**Comment by acoulton** [comment] 2019-04-14 22:57
Brilliant, thanks @JustinBeckwith

**Comment by alexvandervegt** [comment] 2019-06-04 21:11
> @torbjornvatn the PrIoject Editor role, and therefore the default App Engine service account, is not enough to perform backups. Try going into IAM and adding the Cloud Datastore Import Export Admin role to your App Engine service account. This fixed the issue for me.

I just added the role but i still get:

Error: The caller does not have permission

Any more ideas?
