### ISSUE TITLE
JWT Class import issue

### ISSUE THREAD

**Issue by MorpheusZI** [googleapis/google-auth-library-nodejs#1697] opened 2023-11-28 17:22 UTC
I was trying to authenticate a ServiceAccount using JWT by doing doing this :
```Typescript
//... other imports
import { GoogleSpreadSheet } from "google-spreadsheet"
import { JWT } from "google-auth-library"

// ... some other code
const ServiceAccAuth = new JWT({
          email: creds.client_email,
          key: creds.private_key,
          scopes: [
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/drive.file",
          ],
        });
const doc = new GoogleSpreadsheet("MY-SPREADSHEET-ID" ServiceAccAuth);
```

after doing that i got a console error saying "Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/agent-base/dist/index.js (index.ts:29:42)
    at __require2 (chunk-3EJPJMEH.js?v=04702791:15:50)
    at node_modules/https-proxy-agent/dist/index.js (index.ts:7:1)
    at __require2 (chunk-3EJPJMEH.js?v=04702791:15:50)
    at node_modules/gaxios/build/src/gaxios.js (gaxios.ts:33:1)
    at __require2 (chunk-3EJPJMEH.js?v=04702791:15:50)
    at node_modules/gaxios/build/src/index.js (index.ts:15:1)
    at __require2 (chunk-3EJPJMEH.js?v=04702791:15:50)
    at node_modules/gcp-metadata/build/src/index.js (index.ts:8:1)
    at __require2 (chunk-3EJPJMEH.js?v=04702791:15:50)" 
    
Notes: im using React,Typescript and a vite bundler
idek if its a bug or something so i put it on the "bug" type
read online somebody had this issue too said it was an import issue,didnt find any answers i could provide yall with some extra details if ya want

**Comment by danielbankhead** [comment] 2023-11-28 21:18
Hey @MorpheusZI,

This sounds like a duplicate of this issue:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1632

Looking at the error message in the log you posted, it looks like somehow `http.Agent` is `undefined` here:

https://github.com/TooTallNate/proxy-agents/blob/b133295fd16f6475578b6b15bd9b4e33ecb0d0b7/packages/agent-base/src/index.ts#L29C1-L29C49

Perhaps this is an issue with the bundler or configuration you are using?

**Comment by danielbankhead** [comment] 2023-11-30 14:35
@noamolat-fs this sounds like a bundler issue rather than an issue with this library. I’m not sure how else `http.Agent` wouldn’t exist here (referenced in the error message):

https://github.com/TooTallNate/proxy-agents/blob/b133295fd16f6475578b6b15bd9b4e33ecb0d0b7/packages/agent-base/src/index.ts#L29C1-L29C49

**Comment by noamolat-fs** [comment] 2023-11-30 14:46
> @noamolat-fs this sounds like a bundler issue rather than an issue with this library. I’m not sure how else `http.Agent` wouldn’t exist here (referenced in the error message):
> 
> https://github.com/TooTallNate/proxy-agents/blob/b133295fd16f6475578b6b15bd9b4e33ecb0d0b7/packages/agent-base/src/index.ts#L29C1-L29C49

I'm having a hard time with what should I use. I've found these two libraries:
* [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs)
* [google-api-javascript-client](https://github.com/google/google-api-javascript-client)

I was thinking that the issue above was a dependency issue so I switched to the latter, somehow I'm able to access it but now I have a problem with the global type for `gapi`. It's not being recognized by typescript even after installing `@types/gapi` but clearly there's a value for it.

I'm just trying to access a google account's profile information that's all. Am I correct to use the latter one or this library/repo would help me achieve the same?
I'm doing the requests in my Vue app with some sort of service scripts (typescript).

Sorry for the unrelated subjects since I'm just trying to give a better insight into what I'm trying to do. Feel free to just focus on what's related.

**Closed** 2023-11-30 20:36 UTC
Labels: type: question, priority: p2, external, web

**Comment by noamolat-fs** [comment] 2023-12-04 11:57
> > I'm just trying to access a google account's profile information that's all. Am I correct to use the latter one or this library/repo would help me achieve the same?
> 
> I would recommend Google Sign in for this use case:
> 
> * https://developers.google.com/identity/gsi/web/guides/overview
> 
> Related: We’re exploring alternative runtime support, including browsers, for this library. This will be useful for things like admin panels where the customer is a member of a GCP org. This can be tracked here:
> 
> * [feat: Alternate Runtimes Support #1638](https://github.com/googleapis/google-auth-library-nodejs/issues/1638)

Thank you for pointing me in the right direction. I made it work 😁 !

**Comment by zieru** [comment] 2024-01-01 17:33
using this library only to make google-spreadsheet works by using JWT from service account, unfortunately I get this error too. 
I don't have an idea why proxy agent get executed in the browser. 

Building my own api call to get access_token from google is too much works.

**Comment by danielbankhead** [comment] 2024-01-02 19:59
@zieru

> I don't have an idea why proxy agent get executed in the browser.

This library is currently is not designed for the browser. That can be tracked here:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1638

For browser usage today, I would recommend:
- https://developers.google.com/identity/gsi/web/guides/overview
